### ISSUE TITLE
What is the difference of the plugin compared to other plugins

### ISSUE THREAD

**Issue by Vad1mo** [kokuwaio/helm-maven-plugin#107]
I found another similar Maven Plugin that apparently does a similar thing.

Now I am not sure which one should I choose.

Is there some sort of comparison regarding this plugin and https://github.com/deviceinsight/helm-maven-plugin or https://fabric8.io/guide/mavenFabric8Helm.html?

**Comment by kobynet** [comment]
https://github.com/deviceinsight/helm-maven-plugin/issues/75

**Comment by sschnabe** [comment]
Stale
