### ISSUE TITLE
Upload repos not added to helm for the dependency build - required to be added also via helmExtraRepos

### ISSUE THREAD

**Issue by blulic** [kokuwaio/helm-maven-plugin#109]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Environment (plugin version, maven version, OS, ...)**:
Plugin version: 5.7
Maven version: 3.6.3
OS: Linux

**What happened**:
Plugin doesn't add upload repos for resolving dependencies, when chart has defined a dependency to a subchart and that subchart repository is defined via the alias:

Chart has not hardcoded repo URL as we are using different proxies for the Nexus Helm repo depending on the environment:
```
dependencies:
  - name: xxxxxxxx
    version: ~x.x.x
    repository: "@helm-releases"
```

build	06-Feb-2021 09:03:35	[INFO] --- helm-maven-plugin:5.7:init (validate-chart) @ charts ---
build	06-Feb-2021 09:03:35	[INFO] Initializing Helm...
build	06-Feb-2021 09:03:35	[INFO] Creating output directory...
build	06-Feb-2021 09:03:36	[INFO] 
build	06-Feb-2021 09:03:36	[INFO] --- helm-maven-plugin:5.7:dependency-build (validate-chart) @ charts ---
build	06-Feb-2021 09:03:36	[INFO] Build chart dependencies for /home/devtools/bamboo-agent-home2/xml-data/build-dir/XXXXXX/charts/src/main/charts/xxxxx...
build	06-Feb-2021 09:03:36	[ERROR] Error: no repository definition for @helm-releases. Please add them via 'helm repo add'
build	06-Feb-2021 09:03:36	[INFO] ------------------------------------------------------------------------
build	06-Feb-2021 09:03:36	[INFO] BUILD FAILURE

Here's the plugin configuration:
```
  <properties>
    <helmVersion>3.5.2</helmVersion>
    <helmMavenPluginVersion>5.7</helmMavenPluginVersion>
    <helm.downloadUrl>https://get.helm.sh/helm-v${helmVersion}-linux-amd64.tar.gz</helm.downloadUrl>
  </properties>
....
          <plugin>
            <groupId>com.kiwigrid</groupId>
            <artifactId>helm-maven-plugin</artifactId>
            <version>${helmMavenPluginVersion}</version>
            <extensions>true</extensions>
            <configuration>
              <skipUpload>false</skipUpload>
              <chartDirectory>${project.basedir}/src/main/charts/xxxxxxx</chartDirectory>
              <helmVersion>${helmVersion}</helmVersion>
              <useLocalHelmBinary>false</useLocalHelmBinary>
              <appVersion>${project.version}</appVersion>
              <chartVersion>${project.version}</chartVersion>
              <uploadRepoStable>
                <name>helm-releases</name>
                <url>https://xxxxxxxxxxxx/repository/helm-releases/</url>
                <type>ARTIFACTORY</type>
              </uploadRepoStable>
              <uploadRepoSnapshot>
                <name>helm-snapshots</name>
                <url>https://xxxxxxxxx/repository/helm-snapshots/</url>
                <type>ARTIFACTORY</type>
              </uploadRepoSnapshot>
              <addDefaultRepo>false</addDefaultRepo>
            </configuration>
            <executions>
              <execution>
                <id>validate-chart</id>
                <phase>validate</phase>
                <goals>
                  <goal>init</goal>
                  <goal>dependency-build</goal>
                  <goal>lint</goal>
                </goals>
              </execution>
              <execution>
                <id>build-chart</id>
                <phase>package</phase>
                <goals>
                  <goal>package</goal>
                </goals>
              </execution>
              <execution>
                <id>upload-chart</id>
                <phase>deploy</phase>
                <goals>
                  <goal>upload</goal>
                </goals>
              </execution>
            </executions>
          </plugin>
```

Note: this is not a high prio bug as there's workaround to add the same repo via helmExtraRepos:
```
              <helmExtraRepos>
                <helmRepo>
                  <name>helm-releases</name>
                  <url>xxxxxx/repository/helm-releases</url>
                </helmRepo>
              </helmExtraRepos>
```
But, configuring plugin like this defeats DRY principle.

**What you expected to happen**:
I expected that the upload repos are added in the InitMojo. 

**How to reproduce it** (as minimally and precisely as possible):
Define a chart with the dependency to a subchart, which repository is defined as an alias.
Define the uploadRepoStable repository with the same alias.
Run a helm dependency:build goal.

**Anything else we need to know**:

Thanks a lot for the work on the plugin!

With regards,
Boris

**Comment by sschnabe** [comment]
PR was merged. Adding upload repos is now possible.
