### ISSUE TITLE
Support for Helm Install and Helm Uninstall

### ISSUE THREAD

**Issue by smythie86** [kokuwaio/helm-maven-plugin#116]
**Feature Request**
It would be great if functionality could be added to this plugin to support Install and Uninstall helm commands. If bound to pre-integration-test and post-integration-test maven build phases this would allow support for integration testing of the helm chart.

**Comment by sudr** [comment]
I see install is supported. Uninstall could be modeled after that.

**Comment by sschnabe** [comment]
Released with [6.10.0](https://github.com/kokuwaio/helm-maven-plugin/releases/tag/6.10.0).
