### ISSUE TITLE
Add support for OCI-based registry

### ISSUE THREAD

**Issue by vivekweb2013** [kokuwaio/helm-maven-plugin#120]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
**FEATURE REQUEST**

Add the support for using oci registry for pushing helm charts. This feature is supported by Helm 3
- https://helm.sh/docs/topics/registries/#enabling-oci-support

It would be great if this plugin supports this feature. We are using this feature in our CI/CD by manually setting the `HELM_EXPERIMENTAL_OCI=1` flag and using helm cli to push the chart to OCI registry.

The use of oci registry for storing helm charts is increasing day by day and it will be the most used repository type in near future.
So please add support for this feature in this plugin. Thanks.

**Environment (plugin version, maven version, OS, ...)**:
helm 3

**Anything else we need to know**:
This feature is experimental for now, and requires to have the below flag set in env variable
```
export HELM_EXPERIMENTAL_OCI=1
```

**Comment by sr258** [comment]
We could really use this feature as we use the GitLab Docker Registry as our helm repo, which only supports OCI. Having a dedicated Helm Repo would add unnececcesary overhead and maintance costs, so we would really appreciate OCI support.

**Comment by mlkmhd** [comment]
I also need this feature 👍

**Comment by jmabecassis** [comment]
+1 - We really like the plugin but... without an OCI support we won't be able to publish anything into either Harbor or an Azure Container Registry for our firm (big asset manager ;-))

**Comment by sschnabe** [comment]
Fixed with #169, will be released this week with 6.1.0.
