### ISSUE TITLE
[FEATURE REQUEST] Allow --force-update for helm version >= 3.4

### ISSUE THREAD

**Issue by NancyChunlan** [kokuwaio/helm-maven-plugin#127]
**Is this a request for help?**:
yes
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
FEATURE REQUEST

**Environment (plugin version, maven version, OS, ...)**:
helm-maven-plugin 5.9 + helm v3.5.3 
And as checked, for helm <= v3.2, the --repository-cache can not work. and for helm >= v3.3, repository cache works, but if repo already exist and no authentication provided, the exit value would be 1.

**What happened**:
"Unable to add repo" when repo already exist. and repository cache cannot work as expected.
As mentioned in helm v3.4.0 release notes: 
    replace --no-update with --force-update and invert default. BREAKING. 882eeac (Matt Butcher)
And it means from v3.4.0, force update is set as false by default, but true in previous releases.

**What you expected to happen**:
Allow to force update repo in helm-maven-plugin.

**How to reproduce it** (as minimally and precisely as possible):
Consider to use helm-maven-plugin 5.9 and helm v3.5.3, and try to helm init.

**Anything else we need to know**:

**Comment by NancyChunlan** [comment]
@axdotl  Alex, would you mind help for this enhancement?  Thanks very much!

**Comment by axdotl** [comment]
Hi @NancyChunlan ,

as I'm no longer an active maintainer for this project maybe @jekkel or @manu11th can jump in.
