### ISSUE TITLE
Support for aarch64 - apple M1 chip

### ISSUE THREAD

**Issue by koenverwimp** [kokuwaio/helm-maven-plugin#129]
I got the error below on my new Mac with ARM M1 chip.
Would it be possible to support aarch64 in future?

[ERROR] Failed to execute goal com.kiwigrid:helm-maven-plugin:5.9:init (default-init) on project axonserver-docker: Execution default-init of goal com.kiwigrid:helm-maven-plugin:5.9:init failed: Unsupported architecture: aarch64 -> [Help 1]

**Comment by koenverwimp** [comment]
It looks like I found a workaround that would help you to fix it in code:

1) set helmVersion to 3.7.1
2) overwrite the os version to arm64: mvn clean install -Pdocker -Dos.arch=arm64  

Could you please add a mapping to "private String getArchitecture()" to map aarch64 to amd64?

**Comment by elliott-miller** [comment]
Unfortuntaly setting `-Dos.arch=arm64` does not work when used with https://github.com/trustin/os-maven-plugin, that plugin fails with 

```
[ERROR] unknown os.arch: arm64 -> [Help 1]
```
