### ISSUE TITLE
Cannot upload Chart to Nexus when Chart.yaml contains more than 1 dependency

### ISSUE THREAD

**Issue by mhhhkay** [kokuwaio/helm-maven-plugin#130]
**Is this a request for help?**:
Yep!
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Environment (plugin version, maven version, OS, ...)**:
Ubuntu 20.4 LTS
Apache Maven 3.5.0
Java version: 1.8.0_265
plugin version 5.9

**What happened**:
Chart gets properly packaged but cannot get uploaded to Nexus due to

> "Caused by: java.io.IOException: Error writing to server"

**What you expected to happen**:

Chart gets properly uploaded to Nexus

**How to reproduce it** (as minimally and precisely as possible):

1. Create a fresh Chart
2. edit Chart.yaml and add at least 2 dependencies in it
3. configure pom.xml with dependency build goal

					<executions>
						<execution>
							<id>build-chart</id>
							<phase>package</phase>
							<goals>
								<goal>dependency-build</goal>
								<goal>package</goal>
							</goals>
						</execution>
						<execution>
							<id>upload-chart</id>
							<phase>deploy</phase>
							<goals>
								<goal>upload</goal>
							</goals>
						</execution>
					</executions>

4. Package gets properly created but fails to upload.

**Anything else we need to know**:

My overall 6 dependency-charts are combined 134kb of size. so from my perspective nothing much.
If I remove all but one of the dependencies it works perfectly (doesn't matter which dependency i take or remove)

If It try to manually upload the package via curl it works like a charm.
So i suspect nexus is not the issue.

Anyhow by the stacktrace it seems like this snipped is causing the issue:
https://github.com/kiwigrid/helm-maven-plugin/blob/8179d8d10ca305f493181c715747eacdd29ee8c8/src/main/java/com/kiwigrid/helm/maven/plugin/UploadMojo.java

this post here goes pretty much in the same direction and i am wondering if the size really matters here. https://github.com/sbt/sbt/issues/2422

**Stacktrace**

`19:46:36  [ERROR] Failed to execute goal com.kiwigrid:helm-maven-plugin:5.9:upload (upload-chart) on project foo: Error uploading /opt/jenkins_home_3/workspace/foo/target/foo/helm/foo-0.0.11-SNAPSHOT.tgz to https://172.1.1.1:6443/nexus/repository/helm-snapshot-repo/: Error writing to server -> [Help 1]
19:46:36  org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.kiwigrid:helm-maven-plugin:5.9:upload (upload-chart) on project foo: Error uploading /opt/jenkins_home_3/workspace/foo/target/foo/helm/foo-0.0.11-SNAPSHOT.tgz to https://172.1.1.1:6443/nexus/repository/helm-snapshot-repo/
19:46:36      at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
19:46:36      at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
19:46:36      at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
19:46:36      at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
19:46:36      at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
19:46:36      at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
19:46:36      at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
19:46:36      at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
19:46:36      at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
19:46:36      at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
19:46:36      at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
19:46:36      at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
19:46:36      at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
19:46:36      at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
19:46:36      at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
19:46:36      at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
19:46:36      at java.lang.reflect.Method.invoke (Method.java:498)
19:46:36      at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
19:46:36      at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
19:46:36      at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
19:46:36      at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
19:46:36  Caused by: org.apache.maven.plugin.MojoExecutionException: Error uploading /opt/jenkins_home_3/workspace/foo/target/foo/helm/foo-0.0.11-SNAPSHOT.tgz to https://172.1.1.1:6443/nexus/repository/helm-snapshot-repo/
19:46:36      at com.kiwigrid.helm.maven.plugin.UploadMojo.execute (UploadMojo.java:50)
19:46:36      at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
19:46:36      at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
19:46:36      at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
19:46:36      at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
19:46:36      at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
19:46:36      at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
19:46:36      at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
19:46:36      at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
19:46:36      at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
19:46:36      at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
19:46:36      at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
19:46:36      at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
19:46:36      at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
19:46:36      at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
19:46:36      at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
19:46:36      at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
19:46:36      at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
19:46:36      at java.lang.reflect.Method.invoke (Method.java:498)
19:46:36      at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
19:46:36      at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
19:46:36      at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
19:46:36      at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
19:46:36  Caused by: java.io.IOException: Error writing to server
19:46:36      at sun.net.www.protocol.http.HttpURLConnection.writeRequests (HttpURLConnection.java:700)
19:46:36      at sun.net.www.protocol.http.HttpURLConnection.writeRequests (HttpURLConnection.java:712)
19:46:36      at sun.net.www.protocol.http.HttpURLConnection.getInputStream0 (HttpURLConnection.java:1591)
19:46:36      at sun.net.www.protocol.http.HttpURLConnection.getInputStream (HttpURLConnection.java:1498)
19:46:36      at java.net.HttpURLConnection.getResponseCode (HttpURLConnection.java:480)
19:46:36      at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode (HttpsURLConnectionImpl.java:352)
19:46:36      at com.kiwigrid.helm.maven.plugin.UploadMojo.uploadSingle (UploadMojo.java:83)
19:46:36      at com.kiwigrid.helm.maven.plugin.UploadMojo.execute (UploadMojo.java:47)
19:46:36      at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
19:46:36      at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
19:46:36      at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
19:46:36      at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
19:46:36      at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
19:46:36      at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
19:46:36      at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
19:46:36      at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
19:46:36      at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
19:46:36      at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
19:46:36      at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
19:46:36      at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
19:46:36      at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
19:46:36      at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
19:46:36      at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
19:46:36      at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
19:46:36      at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
19:46:36      at java.lang.reflect.Method.invoke (Method.java:498)
19:46:36      at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
19:46:36      at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
19:46:36      at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
19:46:36      at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)

**Chart.yaml**

`apiVersion: v2
appVersion: "1.0"
description: A Helm chart for "foo"
name: "foo"
version: "1.2.3"

dependencies:
  - name: infra-volumes
    repository: https://172.1.1.1:6443/nexus/repository/helm-release-repo/
    version: "1.2.3"
  - name: infra-secrets-assembly
    repository: https://172.1.1.1:6443/nexus/repository/helm-release-repo/
    version: "1.2.3"
  - name: more dependencies` 

Many thanks in advance

**Comment by sschnabe** [comment]
Cannot reproduce, please reopen if this bug is still present
