### ISSUE TITLE
Support gitlab for helmchart upload

### ISSUE THREAD

**Issue by bademeister1** [kokuwaio/helm-maven-plugin#131]
FEATURE REQUEST

Cuttently chartmuseum and artifactory are supported as helm chart registry

gitlab should be supported too.

**Comment by mruzicka** [comment]
Hi, please, note that GitLab _is_ supported via the `push` goal. However this assumes storing the helm charts in the OCI registry.

**Comment by sschnabe** [comment]
Your right. I'll close this ticket. If anybody cannot use OCI please provide a pr.
