### ISSUE TITLE
Open for Adoption

### ISSUE THREAD

**Issue by jekkel** [kokuwaio/helm-maven-plugin#137]
Kiwigrid Teams use Helm since a pretty long time and this plugin has been a important piece for all services built with Maven. That being said, we're moving away from Helm so continuously investing in the maintenance and development of Helm related open source can't be afforded forever.

So with this issue I'd like to inform that we're searching for a new owner and home of this project. If you're interested please comment with some details how you'd like to shape the future of the plugin and how you propose the move to be performed.

**If we won't find a new home we're gonna archive the repository at some point in time.**

**Comment by nazarovkv** [comment]
Can it happen so that key maintainers/owners(let's say @jekkel and @axdotl) will review PRs(at least in terms of code quality) and perform releases once feature merged, while community(contributors) will act as main developers of plugin?

**Comment by nazarovkv** [comment]
Well, anyway.
I can become new owner of this repo...

My plan:
- Together with @jekkel and @axdotl migrate CI/CD on GitHub Actions in order to unlick from KiwiGrid infra(if there is some). I can take care of it.
- Create development manifest. Store it in repo. Considering to have a short call to discuss key agreements.
- Make list of maintainers/contributors in `pom.xml` up-to-date. 
- _Smth else_

**Comment by jekkel** [comment]
> Well, anyway. I can become new owner for this repo...
> 
> My plan:
> 
>     * Together with @jekkel and @axdotl migrate CI/CD on GitHub Actions in order to unlink from KiwiGrid infra(if there is some). I can take care of it.

AFAIK it's built on travis CI, not our infra. So that might be safe already.

> 
>     * Create development manifest. Store it in repo. Considering to have a short call to discuss key agreements.
> 
>     * Make list of maintainers/contributors in `pom.xml` up-to-date.
> 
>     * _Smth else_

My 2 ct on top:

* let's remove `kiwigrid` from the maven groupID and from the java packages
* let's release a last version with unchanged coordinates pointing users to the new coordinates via a warning log
* migrate the repository ownership

That being said I wonder whether you got some supporters for being the maintainer...? Did you already contribute anything? How about pushing some PRs or issues forward as a "proof of work"?

@axdotl Any opinion from you here?

**Comment by nazarovkv** [comment]
Any ideas reg new groupId?

**Comment by nazarovkv** [comment]
> Did you already contribute anything? How about pushing some PRs or issues forward as a "proof of work"?

For now I've raised 3 PRs:
* Two of them my own initiative. 
* One based on opened issue. 

> That being said I wonder whether you got some supporters for being the maintainer...? 

That is the harderst part I guess...

**Comment by nazarovkv** [comment]
> AFAIK it's built on travis CI, not our infra. So that might be safe already.

I'm whishing to have build on PRs. GitHub Actions allow to do that.

**Comment by jekkel** [comment]
I filed a ticket for that one: #139

**Comment by jekkel** [comment]
> Any ideas reg new groupId?

Depends... Do you want to you move the project to your personal account or to an organizational account? I think the hosting entity is usually part of the package name then.

**Comment by jekkel** [comment]
@jschwarze @fabian-schlegel How about your point of view? You've been contributing a lot and might want to take over the project as well?

**Comment by fabian-schlegel** [comment]
I'd like to propose to move the repository together with the corresponding grade plugin to this project: https://github.com/kokuwaio/

For one reason, some of the contributors are also active there, but also the quite popular "helm-charts" project, which is somehow related, lives there.

After moving the projects I can adjust the Maven coordinates and parent POM and even create a release workflow.

**Comment by jekkel** [comment]
That's a great idea! Please consider inviting @nazarovkv as a contributer or maintainer there.

In order to transfer the ownership you need to grant me (temporary) repository creation rights within kokuwa.io org. Note that there's a travis webhook which is going to be transferred as well.

**Comment by jekkel** [comment]
Welcome kokuwa.io :)

@fabian-schlegel Thanks to you and your fellows for stepping in, I'm looking forward to contribute :+1:  

(I think you could relate a PR for renaming everything to this ticket or close it and create a new one)
