### ISSUE TITLE
Feature: support multiple yamlFile values overrides

### ISSUE THREAD

**Issue by gpettey** [kokuwaio/helm-maven-plugin#144]
Helm supports defining multiple files to read values from. This plugin should support the same. Currently only the last `<yamlFile>` entry from the pom is read.

**Comment by nazarovkv** [comment]
While PR is in review, you can pass multiple yaml values via comma separated list :-) 
E.g.:
```xml
<yamlFile>path/to/values-1.yaml,path/to/values-2</yamlFiles>
```

**Comment by nazarovkv** [comment]
PR merged, new version released. Can you please check based on `README.md`

**Comment by nazarovkv** [comment]
@sschnabe should be closed.
