### ISSUE TITLE
Lookup repo details inside settings.xml via its id. (get id based on name from pom.xml)

### ISSUE THREAD

**Issue by nazarovkv** [kokuwaio/helm-maven-plugin#149]
**FEATURE REQUEST**:

**What you expected to happen**:
Follow-up from https://github.com/kiwigrid/helm-maven-plugin/issues/128 to support repo resolution based on name from `pom.xml`.

In order to have smaller/cleaner `pom.xml` it will be more convenient to resolve repository from `settings.xml` by repo-id. 
Repo id <=> repo name from `pom.xml`

**Comment by sschnabe** [comment]
Are you still working on this?

**Comment by nazarovkv** [comment]
Yeah, but it is mostly "nice to have" :-)

**Comment by sschnabe** [comment]
Closing as stale, please reopen when pr is ready.
