### ISSUE TITLE
Plugin output during build contains *****

### ISSUE THREAD

**Issue by smythie86** [kokuwaio/helm-maven-plugin#151]
**Environment (plugin version, maven version, OS, ...)**:
**Maven version:**
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /usr/local/Cellar/maven/3.6.3_1/libexec
Java version: 1.8.0_265, vendor: Amazon.com Inc., runtime: /Library/Java/JavaVirtualMachines/amazon-corretto-8.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.16", arch: "x86_64", family: "mac"

**What happened**:
Info output logs during maven build contain asterisks:

`[INFO] ******H******a******n******g****** ******t******i******g******h******t****** ******w******h******i******l******e****** ******w******e****** ******g******r******a******b****** ******t******h******e****** ******l******a******t******e******s******t****** ******f******r******o******m****** ******y******o******u******r****** ******c******h******a******r******t****** ******r******e******p******o******s******i******t******o******r******i******e******s******.******.******.******`

**What you expected to happen**:
The output should not contain these asterisks:
[INFO] Hang tight while we grab the latest from your chart repositories...

**How to reproduce it** (as minimally and precisely as possible):
Run mvn clean install, invoking the helm-maven-plugin with version 5.10 or 5.11

**Anything else we need to know**:
I think it may be caused by this replace command in case the k8s token is blank: https://github.com/kiwigrid/helm-maven-plugin/blob/master/src/main/java/com/kiwigrid/helm/maven/plugin/AbstractHelmMojo.java#L214

**Comment by stephanschnabel** [comment]
Fixed with release [6.0.0](https://github.com/kokuwaio/helm-maven-plugin/releases/tag/6.0.0).
