### ISSUE TITLE
io.kokuwa.maven:helm-maven-plugin:jar:5.12 is missing from maven central

### ISSUE THREAD

**Issue by haster** [kokuwaio/helm-maven-plugin#157]
**Environment (plugin version, maven version, OS, ...)**:
com.kiwigrid:helm-maven-plugin:jar:5.12
io.kokuwa.maven:helm-maven-plugin:5.12

**What happened**:
The com.kiwigrid:helm-maven-plugin artifact is reported as having moved to com.kiwigrid:helm-maven-plugin but there is no corresponding artifact available for version 5.12 This leads to errors from maven such as:

```
[WARNING] The artifact com.kiwigrid:helm-maven-plugin:jar:5.12 has been relocated to io.kokuwa.maven:helm-maven-plugin:jar:5.12
[WARNING] The POM for io.kokuwa.maven:helm-maven-plugin:jar:5.12 is missing, no dependency information available
[WARNING] Failed to retrieve plugin descriptor for com.kiwigrid:helm-maven-plugin:5.12: Plugin com.kiwigrid:helm-maven-plugin:5.12 or one of its dependencies could not be resolved: io.kokuwa.maven:helm-maven-plugin:jar:5.12 was not found in <our private mirror of maven central> during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of <our mirror> has elapsed or updates are forced
```

The 5.12 version is now hard to use since trying to use it leads to maven downloading the pom from com.kiwigrid, seeing that it has been relocated, trying to download the 5.12 version from io.kokuwa, which is not available on maven central, and giving up with the above error.

**What you expected to happen**:
I expected the 5.12 version to be available in both repos if the intention was that it had been relocated. I expect to be able to use this last 5.x version without having to upgrade to the next major release.

**How to reproduce it** (as minimally and precisely as possible):
Write a pom with a dependency on com.kiwigrid:helm-maven-plugin:jar:5.12 and run any kind of maven command on it, particularly mvn versions:display-plugin-updates

**Anything else we need to know**:

**Comment by sschnabe** [comment]
@haster we will publish a newer Version to central with correct version.

There are no code changes between 5.12 and 6.0.0 (see [changelog](
https://github.com/kokuwaio/helm-maven-plugin/compare/helm-maven-plugin-5.11...6.0.0) except for package renaming and a minor fix for #151.

**Comment by sschnabe** [comment]
[Complete](https://mvnrepository.com/artifact/com.kiwigrid/helm-maven-plugin) relocation to kokuwa done.

**Comment by haster** [comment]
Thanks!
