### ISSUE TITLE
Switch to Java 11

### ISSUE THREAD

**Issue by sschnabe** [kokuwaio/helm-maven-plugin#176]
We should update the min java version from 1.8 to 11.

Why?
 * replace all HttpUrlConnections with java 11 http client
 * some dependencies need 11 (e.g. checkstyle in v10+)
 * java 1.8 is dead
 
Are there any issues upgrading to java 11?

**Comment by nazarovkv** [comment]
Do we really need native Java Http client? Can Feign be cabdidate as well?

**Comment by sschnabe** [comment]
Java HTTP client would be enough. I do not like to have a lot of dependencies.

**Comment by slawekjaranowski** [comment]
unfortunately I must using `JDK 8` .... corpo bleble

**Comment by slawekjaranowski** [comment]
Of course your way is correct - `JDK 1.8` should not be used. 

Proposition: 
- announce plan 
- in next version add warning when user use JDK 1.8 
- give a users some time for preparing eg. 6 months

**Comment by sschnabe** [comment]
From up/down votes i see there are still `JDK 8` users. I'll reopen this issue maybe next year.

**Comment by vliska** [comment]
We use java 11/17 in runtime, but many 3rd party stuff still forces us to build with java 8 and I don't see it going away in close future.
