### ISSUE TITLE
[6.1.0] Cannot login to oci registry in push goal

### ISSUE THREAD

**Issue by SpacePh** [kokuwaio/helm-maven-plugin#178]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Environment (plugin version, maven version, OS, ...)**:
Maven: 3.6.3
Plugin: 6.1.0
OS: Ubuntu 20.04

**What happened**:
The login part of the push goal is not working. This part is skipped if I define a password in the configuration, but if I define the username but no password, the login part is executed (fails because of the missing password).

**What you expected to happen**:
If I define username and password, I expect that the login part is executed.

**Anything else we need to know**:

```
      if (registry.getUsername() != null && registry.getPassword() == null) {
            callCli(
                    getHelmExecuteablePath() +
                            format(
                                    LOGIN_COMMAND_TEMPLATE,
                                    registry.getUsername(),
                                    registry.getUrl()),
                    "can't login to registry", true, registry.getPassword());
        }
```
The PushMojo class have an incorrect condition (line 60 in current 6.1.0 version). The second condition should be:
`registry.getPassword() != null`

**Comment by sschnabe** [comment]
@SpacePh Can you check version [3.1.1-SNAPSHOT](https://oss.sonatype.org/content/repositories/snapshots/io/kokuwa/maven/helm-maven-plugin/6.1.1-SNAPSHOT/)?

**Comment by SpacePh** [comment]
Hello.

Tested that version and I was able to push successfully.

Thanks :)

**Comment by sschnabe** [comment]
[6.1.1](https://search.maven.org/artifact/io.kokuwa.maven/helm-maven-plugin/6.1.1/maven-plugin) is available in maven central.
