### ISSUE TITLE
Ability to optionally specify debug for dry-run

### ISSUE THREAD

**Issue by sudr** [kokuwaio/helm-maven-plugin#179]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

When executing a dry-run it is extremely useful to also optionally specify the "--debug" flag for helm. This spits out the computed values that are useful for debugging.

**Comment by sschnabe** [comment]
Working on it: [debug](https://github.com/kokuwaio/helm-maven-plugin/commit/e597b2729ca61f4bf7aeb033445f50dadeb18724) 

@sudr Feel free to test the branch,

**Comment by sudr** [comment]
Thanks. Unfortunately, I'm on a Apple M1 processor and the work-around mentioned here (https://github.com/kokuwaio/helm-maven-plugin/issues/129) does not work when building this plugin. So I can't build this plugin branch. But the work does work when I use the plugin in my projects.

**Comment by sschnabe** [comment]
A fix for your M1 is implemented and the branch is rebased (to include M1 fix). Can you retry?

**Comment by sudr** [comment]
Thanks for the quick resolution. I tested the debug branch and the -Dhelm.debug flag worked as expected.
