### ISSUE TITLE
Support passing namespace while running lint mojo. 

### ISSUE THREAD

**Issue by nazarovkv** [kokuwaio/helm-maven-plugin#192]
**FEATURE REQUEST**

**Environment (plugin version, maven version, OS, ...)**:
6.3.0

**What happened**:
In case if helm chart has strict dependency on .Release.Namespace property lint command fails.

**Comment by nazarovkv** [comment]
can be achieved by configuring k8sCluster:
```xml
<k8sCluster>
    <namespace>default</namespace>
</k8sCluster>
```

**Comment by nazarovkv** [comment]
Need to consider on extratcting `namespace` property to base mojo.

**Comment by nazarovkv** [comment]
Decided to move all parameters from `k8sCluster` pojo to base abstract mojo.
`k8sCluster` pojo/parameter will be removed in future release.

As of now, not closing issue as reminder to remove `k8sCluster`

**Comment by sschnabe** [comment]
Is this still an issue? Namespace is a parameter in the base mojo. Can i close this ticket?

**Comment by nazarovkv** [comment]
@sschnabe yep, go ahead
