### ISSUE TITLE
Plugin does not recognize parsedVersion variables

### ISSUE THREAD

**Issue by swright-eti** [kokuwaio/helm-maven-plugin#201]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Environment (plugin version, maven version, OS, ...)**:
Plugin version: 6.3.0
Maven version: 3.6.3
OS: Ubuntu 20.04.4 LTS

**What happened**:
When I run ```mvn clean helm:package -DskipTests```  I get the following error:

```    
    [INFO] Setting chart version to ${parsedVersion.majorVersion}.${parsedVersion.minorVersion}.${parsedVersion.incrementalVersion}
    [INFO] Setting App version to 1.3.0-SNAPSHOT
    [ERROR] Error: Invalid Semantic Version
```

**What you expected to happen**:
I expected that the variable names would be substituted for their values. 

**How to reproduce it** (as minimally and precisely as possible):
Add and configure the maven help plugin like this:
```
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>build-helper-maven-plugin</artifactId>
				<version>1.8</version>
				<executions>
				  <execution>
					<id>parse-version</id>
					<goals>
					  <goal>parse-version</goal>
					</goals>
				  </execution>
				</executions>
			</plugin>
```
Configure the helm-maven-plugin like this:
```
			<plugin>
				<groupId>io.kokuwa.maven</groupId>
				<artifactId>helm-maven-plugin</artifactId>
				<version>6.3.0</version>
				<configuration>
					<useLocalHelmBinary>true</useLocalHelmBinary>
					<chartDirectory>${project.basedir}/src/main/helm/device-api</chartDirectory>
				  <chartVersion>${parsedVersion.majorVersion}.${parsedVersion.minorVersion}.${parsedVersion.incrementalVersion}</chartVersion>
				  <appVersion>${project.version}</appVersion>
				</configuration>
			  </plugin>	
```
Then run: ```mvn clean helm:package -DskipTests```

**Anything else we need to know**:
I use the parsedVersions so that when working with SNAPSHOTS my chart version will be valid semver.

**Comment by slawekjaranowski** [comment]
Try with the latest version of `build-helper-maven-plugin` - 3.3.0

Investigate output of `mvn -X ...`  and look how helm plugin is setup by Maven.

**Comment by sschnabe** [comment]
@swright-eti is this still a problem?

**Comment by swright-eti** [comment]
This has been resolved. Thank you.
