### ISSUE TITLE
Bug: pushing to registry requires kubeconfig

### ISSUE THREAD

**Issue by ksharma-qc** [kokuwaio/helm-maven-plugin#270]
Using the push goal prints an error about missing kubeconfig. Building and publishing a helm chart to a repo, should not require a Kubernetes cluster.

This is a fault of helm rather than this maven plugin, but it can provide a way to work around it.

One way to supress this is by using an empty config file and providing it to helm via --kubeconfig flag.

This flag is currently not exposed into the plugin config. Is it possible to add that in please?

**Comment by sschnabe** [comment]
Which helm-version do you use? I cannot reproduce the warning. Can you provide a helm command to enforce this warning?

**Comment by ksharma-qc** [comment]
> Which helm-version do you use? I cannot reproduce the warning. Can you provide a helm command to enforce this warning?

And now I can't reproduce it either.
