### ISSUE TITLE
Allow to push and upload the same chart 

### ISSUE THREAD

**Issue by CondormanFr** [kokuwaio/helm-maven-plugin#276]
I publish my helm chart to a local nexus repository with the "upload" goal and it works fine.

I want to publish my chart to a OCI compliant repository (Azure container registry). It's work fine with the "push" goal.

I want during a few weeks or month publish the same chart on both repository.

Allow the plugin to do that ?

I tried to move the configuration settings in the execution settings but it does not work.

```
<execution>
    <id>Helm-deploy-upload</id>
    <phase>install</phase>
    <goals>
        <goal>upload</goal>
    </goals>
    <configuration>
        <uploadRepoStable>
            <name>nexus3</name>
            <url>http://nexus/repository</url>
            <type>NEXUS</type>
        </uploadRepoStable>                                
    </configuration>
</execution>							
<execution>
    <id>Helm-deploy-push</id>
    <phase>install</phase>
    <goals>
        <!-- <goal>upload</goal> -->
        <goal>push</goal>
    </goals>
    <configuration>
        <uploadRepoStable>
            <name>azure</name>
            <url>xxxxxxxx.azurecr.io/helm</url>
        </uploadRepoStable>                                
    </configuration>    
</execution>
```
Thanks

**Environment (plugin version, maven version, OS, ...)**:
plugin version : 6.6.1
maven 3.9.0

**Comment by sschnabe** [comment]
This should work. Can you provide any error description?

**Comment by vliska** [comment]
I'm using approach for some time (pushing to nexus & to azure via OCI), so it definitely works.

Example:
`
...
              <execution>
                <id>helm-deploy-nexus</id>
                <phase>deploy</phase>
                <goals>
                  <goal>upload</goal>
                </goals>
                <configuration>
                  <uploadRepoStable>
                    <name>nexus-server-id<name>
                    <url>nexus-url</url>
                    <type>NEXUS</type>
                  </uploadRepoStable>
                </configuration>
              </execution>
              <execution>
                <id>helm-upload-azure</id>
                <phase>deploy</phase>
                <goals>
                  <goal>push</goal>
                </goals>
                <configuration>
                  <uploadRepoStable>
                    <name>azure-server-address</name>
                    <url>azure-oci-helm-repo-url</url>
                  </uploadRepoStable>
                </configuration>
              </execution>
...

`

**Comment by CondormanFr** [comment]
Yes, it work in fact. 👍 

For testing purpose , I was using 
`mvn helm:upload`
and i get the error :
`[ERROR] Failed to execute goal io.kokuwa.maven:helm-maven-plugin:6.6.1:upload (default-cli) on project solvnet-nps: Execution default-cli of goal io.kokuwa.maven:helm-maven-plugin:6.6.1:upload failed: Cannot invoke "io.kokuwa.maven.helm.pojo.HelmRepository.getUrl()" because "uploadRepoStable" is null -> [Help 1]`

but when running 
`mvn install `
it works despite the error log level flag

```
[INFO] --- helm:6.6.1:push (Helm-deploy-push) @ project  ---
[ERROR] Login Succeeded
[INFO] Uploading d:\pathto\target\helm\repo\project-1.0.0-SNAPSHOT.tgz...
[ERROR] Pushed: xxxxxxxx.azurecr.io/helm/project:1.0.0-SNAPSHOT
[ERROR] Digest: sha256:0642c6fd35ac903109101d66fc8d3b78da010b4b1fd9b659a91b8637516857ed
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  56.812 s
[INFO] Finished at: 2023-03-14T15:05:26+01:00
[INFO] ------------------------------------------------------------------------
```
Thanks, you save me !
