### ISSUE TITLE
Upload path created always has version first

### ISSUE THREAD

**Issue by Pallavi810** [kokuwaio/helm-maven-plugin#286]
**Is this a request for help** no

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Environment (plugin version, maven version, OS, ...)**:
Plugin version is 6.4.0

**What happened**:
The class UploadMojo only uses project group Id as the path where it uploads and then appends with version only. Instead the path should be groupid+artifactid inside of white a chart should be present. Otherwise it's not organized.

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):
Just upload any chart to artifactory.
**Anything else we need to know**:

**Comment by sschnabe** [comment]
@Pallavi810 in #287 i've added a flag to use the artifactId instead of groupId or in combination with groupId.
Please verify if #287 matches your requirements.

**Comment by Pallavi810** [comment]
Yes this works

**Comment by sschnabe** [comment]
Release with [6.7.0](https://github.com/kokuwaio/helm-maven-plugin/releases/tag/6.7.0)
