### ISSUE TITLE
Helm package manager is not downloading with <helmDownloadUrl

### ISSUE THREAD

**Issue by ccfahe** [kokuwaio/helm-maven-plugin#292]
**Is this a request for help?**:
It is a help and may be a bug too

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug report

**Environment (plugin version, maven version, OS, ...)**:
plugin version 6.7.0 ,mvn 3.8.6,Linux 

**What happened**:
I want to download helm package manager using helm-maven plugin instead of manually downloading in the build machine but the  <helmDownloadUrl>https://get.helm.sh/helm-v3.8.2-linux-amd64.tar.gz</helmDownloadUrl> does not work and I got below error

] Failed to execute goal io.kokuwa.maven:helm-maven-plugin:6.7.0:dependency-build (helm-package) on project spring-rest-hello-world: Helm executable not found. 

**What you expected to happen**:
I want to download helm package manager using helm-maven plugin instead of manually downloading in the build machine

**How to reproduce it** (as minimally and precisely as possible):
mvn clean package

**Anything else we need to know**:
Other config:
  <chartDirectory>${project.basedir}</chartDirectory>
                    <chartVersion>${helm.chart.version}</chartVersion>
                    <helmDownloadUrl>https://get.helm.sh/helm-v3.8.2-linux-amd64.tar.gz</helmDownloadUrl>
                    <autoDetectLocalHelmBinary>false</autoDetectLocalHelmBinary>
                    <useLocalHelmBinary>false</useLocalHelmBinary>

**Comment by sschnabe** [comment]
Did you run `mvn helm:init`? Can you provide the logs for `mvn helm:init -X`?

**Comment by ccfahe** [comment]
I guess I missed this,Thanks for the help,it worked :)
