### ISSUE TITLE
plugin downloads wrong binary architecture version on mac with apple silicon

### ISSUE THREAD

**Issue by daviddavidgit** [kokuwaio/helm-maven-plugin#331]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Environment (plugin version, maven version, OS, ...)**:

- plug-in version: 6.8.0
- Apache Maven 3.9.4
- macOs Ventura Version 13.4

**What happened**:

When using helm-maven-plugin on my mac (with apple silicon chip) it downloads a amd binary version of helm.

**What you expected to happen**:

When using helm-maven-plugin on a mac (with apple silicon chip) it should download the arm binary version of helm.

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

PR #332

**Comment by sschnabe** [comment]
aarch64 is arm based, strange that no one ever complained before

**Comment by sschnabe** [comment]
@daviddavidgit Thanks for your contribution. Is released as [6.11.1](https://github.com/kokuwaio/helm-maven-plugin/releases/tag/6.11.1), should be available in a hour at maven-central.

**Comment by daviddavidgit** [comment]
@sschnabe Thanks for the release, it seems that the the new version is not published at maven-central.

**Comment by sschnabe** [comment]
@daviddavidgit i can see it here: https://repo1.maven.org/maven2/io/kokuwa/maven/helm-maven-plugin/6.11.1/

**Comment by daviddavidgit** [comment]
strange that it does not show up here: https://central.sonatype.com/artifact/io.kokuwa.maven/helm-maven-plugin/versions
