### ISSUE TITLE
Support for --plain-http flag in order to upload/download charts from OCI registries served at an HTTP endpoint

### ISSUE THREAD

**Issue by danparisi** [kokuwaio/helm-maven-plugin#336]
FEATURE REQUEST
Supporting _--plain-http_ flag when running following commands:
- helm install
- helm pull
- helm push
- helm template
- helm upgrade
- helm show

The flag was added in _Helm v3.13.0_ in order to instructs the registry client to use plain HTTP connections, thus enabling upload/download of charts from _OCI_ registries served at an HTTP endpoint.

More information can be found here:
https://github.com/helm/helm/pull/12128

**Comment by danparisi** [comment]
@sschnabe do you think you will have some capacity for such implementation?

**Comment by sschnabe** [comment]
Released with [6.12.0](https://github.com/kokuwaio/helm-maven-plugin/releases/tag/6.12.0)
