### ISSUE TITLE
Configuration tags kubeAsUser and kubeAsGroup are mixed up 

### ISSUE THREAD

**Issue by tipame** [kokuwaio/helm-maven-plugin#388]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Environment (plugin version, maven version, OS, ...)**:
plugin version: 6.16.0
mvn version: 3.8.1
helm version: 3.16.3

**What happened**:
Configuration tags <kubeAsUser> and <kubeAsGroup> are mixed up. 
Using **kubeAsUser** tag brings helm option **--kube-as-group**
Using **kubeAsGroup** tag brings helm option **--kube-as-user**

Not tested with helm.kubeAsUser and helm.kubeAsGroup properties.

**Comment by slawekjaranowski** [comment]
The bug is here:

https://github.com/kokuwaio/helm-maven-plugin/blob/97c033ac758ab8efd9632739b3fc4319f58ed4d3/src/main/java/io/kokuwa/maven/helm/AbstractHelmMojo.java#L344-L345

**Comment by sschnabe** [comment]
Released with [6.17.0](https://github.com/kokuwaio/helm-maven-plugin/releases/tag/6.17.0)
