### ISSUE TITLE
dependency-build should be run before lint

### ISSUE THREAD

**Issue by slawekjaranowski** [kokuwaio/helm-maven-plugin#81]
**BUG REPORT** :
**Environment (plugin version, maven version, OS, ...)**: 5.3

When project has dependency in Chart.yaml below configuration doesn't work:
```
<plugin>
    <groupId>com.kiwigrid</groupId>
    <artifactId>helm-maven-plugin</artifactId>
    <version>5.3</version>
    <executions>
        <execution>
            <id>helm</id>
            <goals>
                <goal>init</goal>
                <goal>dependency-build</goal>
                <goal>lint</goal>
                <goal>package</goal>
                <goal>upload</goal>
            </goals>
        </execution>
    </executions>
    <configuration>
    </configuration>
</plugin>

``` 
because goal `dependency-build` is run after `lint`, so dependency is not resolved.

`dependency-build` is bind to `prepare-package` phase and `lint` is bind to `test` phase. 

`dependency-build` should be bind to some earlier phase, maybe `compile`

This configuration is workaround:

```
<plugin>
    <groupId>com.kiwigrid</groupId>
    <artifactId>helm-maven-plugin</artifactId>
    <version>5.3</version>
    <executions>
        <execution>
            <id>helm-init</id>
            <phase>initialize</phase>
            <goals>
                <goal>init</goal>
            </goals>
        </execution>
        <execution>
            <id>helm-update</id>
            <phase>compile</phase>
            <goals>
                <goal>dependency-build</goal>
            </goals>
        </execution>
        <execution>
            <id>helm</id>
            <goals>
                <goal>lint</goal>
                <goal>package</goal>
                <goal>upload</goal>
            </goals>
        </execution>
    </executions>
    <configuration>
    </configuration>
</plugin>
```

**Packaging with the Helm Lifecycle**
I suspect that Packaging with the Helm Lifecycle also will not work for chart with dependency.

We have in plugin life cycle configuration:
```
<lifecycle>
    <id>default</id>
    <phases>
        <initialize>com.kiwigrid:helm-maven-plugin:init</initialize>
        <test>com.kiwigrid:helm-maven-plugin:lint</test>
        <package>com.kiwigrid:helm-maven-plugin:package</package>
        <deploy>com.kiwigrid:helm-maven-plugin:upload</deploy>
    </phases>
</lifecycle>
```

so goal `dependency-build` is not bind to any phase

**What you expected to happen**:
build pass

**Comment by thomschke** [comment]
see #101

**Comment by slawekjaranowski** [comment]
@thomschke - Your change resolve second case from my issue. Thanks.

Still we need change binding of dependency-build goal.

**Comment by slawekjaranowski** [comment]
current binding:

```xml
<phases>
    <initialize>io.kokuwa.maven:helm-maven-plugin:init</initialize>
    <test>io.kokuwa.maven:helm-maven-plugin:lint</test>
    <prepare-package>io.kokuwa.maven:helm-maven-plugin:dependency-build</prepare-package>
    <package>io.kokuwa.maven:helm-maven-plugin:package</package>
    <deploy>io.kokuwa.maven:helm-maven-plugin:upload</deploy>
</phases>
```

what do you think to change to:

```xml
<phases>
    <initialize>io.kokuwa.maven:helm-maven-plugin:init</initialize>
    <generate-resources>io.kokuwa.maven:helm-maven-plugin:dependency-build</generate-resources>
    <test>io.kokuwa.maven:helm-maven-plugin:lint</test>
    <package>io.kokuwa.maven:helm-maven-plugin:package</package>
    <deploy>io.kokuwa.maven:helm-maven-plugin:upload</deploy>
</phases>
```

`dependency-build` will be executed in phase `generate-resources` before `lint`

**Comment by vliska** [comment]
Hi,

this would destroy a lot of our builds (generate-resources is too soon - we stage helm charts, incl. patches in target/ to values.yaml, etc. - in these phases).


I also believe such change would require major version bump.


BR,

Vojtech

________________________________
Od: Slawomir Jaranowski ***@***.***>
Odesláno: čtvrtek 24. března 2022 10:37:33
Komu: kokuwaio/helm-maven-plugin
Kopie: Subscribed
Předmět: Re: [kokuwaio/helm-maven-plugin] dependency-build should be run before lint (#81)


current binding:

<phases>
    <initialize>io.kokuwa.maven:helm-maven-plugin:init</initialize>
    <test>io.kokuwa.maven:helm-maven-plugin:lint</test>
    <prepare-package>io.kokuwa.maven:helm-maven-plugin:dependency-build</prepare-package>
    <package>io.kokuwa.maven:helm-maven-plugin:package</package>
    <deploy>io.kokuwa.maven:helm-maven-plugin:upload</deploy>
</phases>

what do you think to change to:

<phases>
    <initialize>io.kokuwa.maven:helm-maven-plugin:init</initialize>
    <generate-resources>io.kokuwa.maven:helm-maven-plugin:dependency-build</generate-resources>
    <test>io.kokuwa.maven:helm-maven-plugin:lint</test>
    <package>io.kokuwa.maven:helm-maven-plugin:package</package>
    <deploy>io.kokuwa.maven:helm-maven-plugin:upload</deploy>
</phases>

dependency-build will be executed in phase generate-resources before lint

**Comment by slawekjaranowski** [comment]
For me any phase will be ok if  `dependency-build` will be executed before `lint`.
So phase for `lint` can also be changed from `test` to something else.

Any other proposition?

**Comment by slawekjaranowski** [comment]
This one issue is blocking for me for using helm-packaging. 
As I see implementation is easy, the most difficult is to find proper binding for goals. 

Order of goals should be:
 - init
 - dependency-build
 - lint
 - package
 - upload
 
Maybe `process-classes` will be ok for `dependency-build` it is after `generate-resources`

https://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html

**Comment by sschnabe** [comment]
Why `process-classes` and not `process-resources`? Any advantages or disadvantages? Both are after `generate-resources`.

**Comment by slawekjaranowski** [comment]
`process-resources` is ok, is after `generate-resources` and before `test`

**Comment by sschnabe** [comment]
@slawekjaranowski can you provide a pr with an invoker test using goals `helm:init`, `helm:dependency-build` and `helm:lint`?

**Comment by slawekjaranowski** [comment]
@sschnabe invoker tests added
