### ISSUE TITLE
Pushing to Harbor which requires a ca cert

### ISSUE THREAD

**Issue by MiellyEllen** [kokuwaio/helm-maven-plugin#83]
**Is this a request for help?**:
YES
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
FEATURE REQUEST

**Environment (plugin version, maven version, OS, ...)**:
Any

**What happened**:
mvn plugin does not support pushing image to Harbor with ca cert

**What you expected to happen**:
would like an option to push and provide a path to a ca cert file

**How to reproduce it** (as minimally and precisely as possible):
N/A

**Anything else we need to know**:
Does anyone know of an existing helm mvn plugin that already supports this?

**Comment by edrandall** [comment]
cacerts file is in JAVA_HOME/[jre]/lib/security/cacerts
You could either:
1) Update that cacerts file with your server's cert, using keytool -importcert
2) Create an alternate cacerts file and -Djavax.net.ssl.trustStore=/path/to/alternate/cacerts

**Comment by steromano87** [comment]
I had the same issue and opened this ticket to support the `insecure` flag (available from version 6.7.0) also on the `push` goal: https://github.com/kokuwaio/helm-maven-plugin/issues/302
