### ISSUE TITLE
Automatic Download of Helm Client doesn't seem to honor maven proxy settings.

### ISSUE THREAD

**Issue by Deklin** [kokuwaio/helm-maven-plugin#91]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Environment (plugin version, maven version, OS, ...)**:
Linux/CentOS

**What happened**:
When running 
```
 mvn helm:init  helm:dependency-build  helm:package
``` 
in our CICD system we continue to get a certificate error, even when disabling maven certificate checks, I believe after looking at the helm plugin code that it may be ignoring the maven proxy config since it is using URL openstream directly.

![image](https://user-images.githubusercontent.com/3372511/88860577-18545380-d1ca-11ea-9b7e-eaeaac2faecd.png)

**What you expected to happen**:
Helm client should download

**How to reproduce it** (as minimally and precisely as possible):
Attempt to run helm:init in an environment that requires a proxy. Ensure your proxy is configured in settings.xml

**Anything else we need to know**:

**Comment by alimfeld** [comment]
It would definitely be nice, if proxy settings were honored by the plugin.

One way to make the plugin work behind a proxy is to pass the proxy settings as system properties to the mvn build:

`mvn -Dhttps.proxyHost=<your-proxy-host> -Dhttps.proxyPort=<your-proxy-port>` (and/or `http.proxyHost`, `http.proxyPort`).

However, if your using the maven-release-plugin a VM is forked during the build. In this case you have to supply the proxy settings via the `arguments` property: `-Darguments="-https.proxyHost=<your-proxy-host> -Dhttps.proxyPort=<your-proxy-port>"`

**Comment by sschnabe** [comment]
Fixed with [6.9.0](https://github.com/kokuwaio/helm-maven-plugin/releases/tag/6.9.0).
