### ISSUE TITLE
Tar file produces warnings upon extraction: implausibly old time stamp 1970-01-01 01:00:00

### ISSUE THREAD

**Issue by danielburrell** [kokuwaio/helm-maven-plugin#93]
**Is this a request for help?**:
No
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Environment (plugin version, maven version, OS, ...)**:
Linux centos7, Maven 3. plugin 5.4

**What happened**:
` mvn clean package helm:init helm:dependency-build helm:package`
produces a tar file, which when extracted produces the warnings
` implausibly old time stamp 1970-01-01 01:00:00`

It's quite noisy, and to work around we must suppress warnings, which isn't ideal.

**What you expected to happen**:
No warnings upon extraction - probably as a result of plausible timestamps.

**How to reproduce it** (as minimally and precisely as possible):
Create a helm chart
Run ` mvn clean package helm:init helm:dependency-build helm:package`
run `tar xvzf chartfilearchive`

**Anything else we need to know**:

**Comment by sschnabe** [comment]
Cannot reproduce. Please reopen this issue is still present on your maschine. This is an old ticket, i expect this issue was fixed meanwhile.
