### ISSUE TITLE
Pushing to CHART MUSEUM repos with authentication

### ISSUE THREAD

**Issue by cfontes** [kokuwaio/helm-maven-plugin#99]
**Is this a request for help?**:

When using this plugin with Chart Museum on https://charts.banzaicloud.io, I cannot push to it as it needs an authentication token

One can make the plugin work by adding this ENV_VAR 

`export HELM_REPO_ACCESS_TOKEN=************`

But this maven plugin ignores it, possibly because it does not use Helm Push Plugin, but would be possible to add bearer tokens in the same fashion?

**Environment (plugin version, maven version, OS, ...)**:
Apache Maven 3.6.1
Maven home: /usr/share/maven
Java version: 11.0.7, vendor: Ubuntu, runtime: /usr/lib/jvm/java-11-openjdk-amd64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.3.0-64-generic", arch: "amd64", family: "unix"

**What happened**:
Fails to authenticate
 {"error":"unauthorized"}

**What you expected to happen**:
Be able to authenticate and push to the private repo

**How to reproduce it** (as minimally and precisely as possible):
Create a private repo on banzai and configure this plugin as CHART MUSEUM

**Comment by sschnabe** [comment]
Authentication is possible with `setttings.xml` of maven. If this is not sufficient please reopen.
